# Generated by Django 4.2.4 on 2023-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='Уникальное соответствие рецепта пользователю в favorite',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='Уникальное соответствие названия мере измерения',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='Уникальное соответствие ингредиента рецепту',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='Уникальное соответствие рецепта пользователю в shoppingcart',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Соответствие рецепта пользователю в favorite'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='Соответствие названия мере измерения'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Соответствие ингредиента рецепту'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Соответствие рецепта пользователю в shoppingcart'),
        ),
    ]
